export const PRODUCTDETAIL_REQUEST = '@productDetail/PRODUCTDETAIL_REQUEST'
export const PRODUCTDETAIL_SUCCESS = '@productDetail/PRODUCTDETAIL_SUCCESS'
export const PRODUCTDETAIL_FAILED = '@productDetail/PRODUCTDETAIL_FAILED'
export const COMMENT_PRODUCT_DETAIL_REQUEST = "@productDetail/COMMENT_PRODUCT_DETAIL_REQUEST";
export const COMMENT_PRODUCT_DETAIL_SUCCESS = "@productDetail/COMMENT_PRODUCT_DETAIL_SUCCESS";
export const COMMENT_PRODUCT_DETAIL_FAILED = "@productDetail/COMMENT_PRODUCT_DETAIL_FAILED";
