export const PRODUCTDETAIL_REQUEST = '@productDetail/PRODUCTDETAIL_REQUEST'
export const PRODUCTDETAIL_SUCCESS = '@productDetail/PRODUCTDETAIL_SUCCESS'
export const PRODUCTDETAIL_FAILED = '@productDetail/PRODUCTDETAIL_FAILED'